# -*- encoding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(blank=True, choices=[('F', 'Familiar'), ('P', 'Parelles'), ('E', 'Endurance')], max_length=1, null=True)),
                ('temps', models.CharField(max_length=10)),
                ('km', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('imatge', models.CharField(max_length=200)),
                ('opinio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='comentari',
            name='comentari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campingbike.Ruta'),
        ),
    ]
