# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingbike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('tipus', models.CharField(blank=True, choices=[('F', 'Familiar'), ('P', 'Parelles'), ('E', 'Endurance')], max_length=1, null=True)),
                ('temps', models.CharField(max_length=10)),
                ('km', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('imatge', models.CharField(max_length=200)),
                ('opinio', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='imatge',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='km',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='link',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='opinio',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='temps',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='tipus',
        ),
        migrations.AddField(
            model_name='ruta',
            name='Latitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='Longitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
