# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingbike', '0003_auto_20190510_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentari',
            name='nom',
        ),
        migrations.AddField(
            model_name='comentari',
            name='nom',
            field=models.ManyToManyField(to='campingbike.Ruta'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='track',
            name='ruta',
        ),
        migrations.AddField(
            model_name='track',
            name='ruta',
            field=models.ManyToManyField(to='campingbike.Ruta'),
        ),
    ]
