# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingbike', '0004_auto_20190510_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentari',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='comentari',
            name='tipus',
        ),
        migrations.RemoveField(
            model_name='track',
            name='ruta',
        ),
        migrations.AddField(
            model_name='ruta',
            name='comentari',
            field=models.ManyToManyField(to='campingbike.Comentari'),
        ),
    ]
