# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingbike', '0005_auto_20190510_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='track',
            field=models.ManyToManyField(to='campingbike.Track'),
        ),
    ]
