# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-10 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campingbike', '0006_ruta_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='comentari',
            field=models.ManyToManyField(null=True, to='campingbike.Comentari'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='track',
            field=models.ManyToManyField(null=True, to='campingbike.Track'),
        ),
    ]
